"""
Django settings

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('CEI_NEXUS_SECRET_KEY', 'h1kuvl)j#e6_7rbhr&f@_3%)$nle*b8t$82wta*e3wu-(5v$$o')

# SECURITY WARNING: do not run with debug turned on in production!
DEBUG = int(os.environ.get('CEI_NEXUS_DEBUG', '0')) == 1

BETA_FLAG = os.environ.get('ENSIGHT_ANSYS_BETA_FLAG', '0') != '0'

# todo: remove and use from ADR() instance.
CEI_APEX_SUFFIX = "242"

# https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.admindocs',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'guardian',
    'ansys.dynamicreporting.core.internals.ceireports',
    'ansys.dynamicreporting.core.internals.website',
    'ansys.dynamicreporting.core.internals.data.apps.DataConfig',
    'ansys.dynamicreporting.core.internals.reports',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'data.context_processors.debug',
                'django.template.context_processors.media',
                'data.context_processors.global_settings',
            ],
        },
    },
]

# pick the SQLite database to use or use the remote config
local_db_dir = os.environ.get('CEI_NEXUS_LOCAL_DB_DIR', None)
# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
if local_db_dir is not None:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(local_db_dir, 'db.sqlite3'),
            'USER': 'nexus',
            'PASSWORD': 'cei',
            'HOST': '',
            'PORT': '',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': os.environ.get('CEI_NEXUS_DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.environ.get('CEI_NEXUS_DB_DATABASE_NAME', 'nexus_database'),
            'USER': os.environ.get('CEI_NEXUS_DB_USER', 'nexus'),
            'PASSWORD': os.environ.get('CEI_NEXUS_DB_PASSWORD', 'cei'),
            'HOST': os.environ.get('CEI_NEXUS_DB_HOSTNAME', '127.0.0.1'),
            'PORT': os.environ.get('CEI_NEXUS_DB_PORT', '5432'),
        }
    }

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

# This enables timezone support.
# If True:
# 1. datetime objects MUST be saved with timezone('aware'). If not aware,
# Django uses the default timezone('TIME_ZONE') to make it aware, which is unreliable,
# so always specify tzinfo in datetimes.
# 2. Values are still stored in UTC in the DB, but are translated by Django/DRF
# into the end user's timezone using internal tz-aware datetime objects.
# If False, values are stored as naive (without tzinfo), but in local time (as per 'TIME_ZONE')
# NEVER SET THIS TO FALSE.
USE_TZ = True

# default timezone used for template display.
# 1. If the current timezone is not set in Django with activate(),
# this setting is used as a fallback.
# Read: https://docs.djangoproject.com/en/2.2/topics/i18n/timezones/#default-time-zone-and-current-time-zone
# 2. When USE_TZ is False, this is the time zone in which Django will store all datetimes.
# When USE_TZ is True, this is the default time zone that Django will use to display datetimes in templates
# and to interpret datetimes entered in forms.
# 3. If you're running Django on Windows, TIME_ZONE must be set to match the system time zone.
# 'TIME_ZONE' needs to be in Olson format which
# can be very platform and system configuration dependent to set.
if 'CEI_NEXUS_TIMEZONE' in os.environ:
    TIME_ZONE = os.environ['CEI_NEXUS_TIMEZONE']
else:
    import tzlocal

    TIME_ZONE = str(tzlocal.get_localzone())

USE_I18N = True  # enable translation

# Absolute filesystem path to the directory that will hold user-uploaded files.
# Example: "/home/media/media.lawrence.com/media/"
# This can be local to the installation of the sources or local to the folder contain the database
media_dir = os.environ.get('CEI_NEXUS_LOCAL_MEDIA_DIR', local_db_dir or BASE_DIR)

# Unlike static files, in order to serve media files,
# the url has to be manually specified even while using the runserver + DEBUG.
# so we handle this in ceireports/urls.py
# https://docs.djangoproject.com/en/dev/howto/static-files/#serving-files-uploaded-by-a-user-during-development
# Replace '\\' in Windows. Django only accepts Unix-style paths
# This is the Absolute filesystem path to the directory that will hold user-uploaded files.
# Example: "/var/www/files/"
MEDIA_ROOT = os.path.join(media_dir, "media").replace('\\', '/')

# URL that handles the media served from MEDIA_ROOT.
# must end in a slash if set to a non-empty value.
# Examples: "http://media.lawrence.com/media/", "http://example.com/media/"
MEDIA_URL = os.environ.get('CEI_NEXUS_MEDIA_URL_PREFIX', '/media/')

# 1. ONLY used for the collectstatic command.
# 2. Absolute path to the directory static files should be collected to.
# 3. When using nginx, this should be the directory nginx will be serving out of.
# 4. Don't put anything in this directory yourself; store your static files
# in apps' "static/" subdirectories and in other STATICFILES_DIRS.
# Example: "/home/media/media.lawrence.com/static/"
# similar to MEDIA_ROOT, but for static file serves
STATIC_ROOT = os.path.join(BASE_DIR, 'static').replace('\\', '/')

# relative URL to use when referring to static files located in STATIC_ROOT.
STATIC_URL = '/static/'

# if true, media files via the Django built-in server
# this will be disabled by launcher when using Nginx to serve.
SERVE_STATIC = int(os.environ.get('CEI_NEXUS_SERVE_STATIC_FILES', '1')) == 1

# ACLs switch.
ENABLE_ACLS = int(os.environ.get('CEI_NEXUS_ENABLE_ACLS', 0)) == 1
