# -*- coding: utf-8 -*-
"""
# *************************************************************
#  Copyright 2019-2022 ANSYS, Inc.
#  All Rights Reserved.
#
#  Restricted Rights Legend
#
#  Use, duplication, or disclosure of this
#  software and its documentation by the
#  Government is subject to restrictions as
#  set forth in subdivision [(b)(3)(ii)] of
#  the Rights in Technical Data and Computer
#  Software clause at 52.227-7013.
# *************************************************************

Django settings for the Nexus project.

Generated by 'django-admin startproject' using Django 1.8.12.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# CEI configuration environmental variables:
#
# CEI_NEXUS_TIMEZONE - the Olson format timezone for the server.  used in formatting time
# CEI_NEXUS_LOCAL_DB_DIR - pathname to the directory where the SQLite database file is
# CEI_NEXUS_LOCAL_MEDIA_DIR - pathname to the directory where the media directory is
# CEI_NEXUS_MEDIA_URL_PREFIX - URL prefix used to access /media remotely (/media/ is the default, needs trailing '/')
# CEI_NEXUS_LOCAL_ALLOW_REMOTE_ACCESS - if set to anything, allows remote access to a local DB server
# CEI_NEXUS_SERVE_STATIC_FILES - True if the Django built-in server should serve static and media files
# CEI_NEXUS_DB_ENGINE - database engine to use.  Default: django.db.backends.postgresql_psycopg2
# CEI_NEXUS_DB_DATABASE_NAME - database table to use.  Default: nexus_database
# CEI_NEXUS_DB_USER - database username.  Default: nexus
# CEI_NEXUS_DB_PASSWORD - database password.  Default: cei
# CEI_NEXUS_DB_HOSTNAME - database hostname.  Default: 127.0.0.1
# CEI_NEXUS_DB_PORT - database port.  Default: 5432
# CEI_NEXUS_SERVER_NAME - the (human) name of the server.  Default: mixed
# CEI_NEXUS_SECRET_KEY - the Django secret key to use for this instance.  Default: built-in key
# If using sqlite, the default is the directory name of the SQLite file, otherwise: ''
# CEI_NEXUS_ALLOWED_HOSTS - a comma separated list of hosts that can access your remote server.
# eg: localhost, 127.0.0.1,
# CEI_NEXUS_HTTPS_SECURED - HTTPS specify settings. Should only be turned on if your entire domain
# is served via HTTPS only.
# CEI_NEXUS_HSTS_SECURED - Enable HTTP Strict Transport Security.
# Read https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security
# CEI_NEXUS_HSTS_SECONDS - Number of seconds that HSTS header should be respected by the browser.
# Setting this incorrectly can irreversibly (for the value of SECURE_HSTS_SECONDS) break your site.
#
# CEI_NEXUS_X_FRAME_OPTIONS - set the X-Frame-Options header globally for all responses
# CEI_NEXUS_ENABLE_ACLS - Per-category ACLs switch. Still WIP, DO NOT DOCUMENT.
# CEI_NEXUS_ACLS_NGINX_LOCATION - This is the location value of the NGINX configuration where the media file
# request URLs are directed to. It is the location directive where nginx “hides” permission-checked files
# from general access. Default value is /media_secured
# If using the default value, your NGINX config would look like:
# location /media_secured {
#   internal;
#   alias /var/www/files;
# }
# Will serve /var/www/files/myfile.png
# When Nexus sets header which will be /media_secured/myfile.png
# `internal` is very important.
# It makes sure that location can only be
# redirected to or accessed internally
#
# Optional remote session configuration
# CEI_NEXUS_REMOTE_WEBSOCKETURL - the URL of the Nginx server connection mapped to websocketserver
# CEI_NEXUS_REMOTE_WS_PORT - the port the websocketserver server talks the "ws" protocol to Nginx over
# CEI_NEXUS_REMOTE_HTML_PORT - the port the websocketserver server talks the "http" rest protocol
# CEI_NEXUS_REMOTE_VNCPASSWORD - the password for a VNC server
#
# Note: a non-debug local server needs to be run with:
# manage.py runserver --insecure 0.0.0.0:8000
# The --insecure enables static file distribution in runserver.

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('CEI_NEXUS_SECRET_KEY', 'h1kuvl)j#e6_7rbhr&f@_3%)$nle*b8t$82wta*e3wu-(5v$$o')

# Autogenerated by the Nexus launcher.  Used to secure communication with the websocket server
WEBSOCKETSERVER_SECURITY_TOKEN = os.environ.get('WEBSOCKETSERVER_SECURITY_TOKEN', '')

# SECURITY WARNING: do not run with debug turned on in production!
DEBUG = int(os.environ.get('CEI_NEXUS_DEBUG', '0')) == 1

# ANSYS BETA FLAG: '0' is False, everything else is True
BETA_FLAG = os.environ.get('ENSIGHT_ANSYS_BETA_FLAG', '0') != '0'

# guess the name of the CEI APEX system
try:
    import enve
    import ceiversion

    CEI_APEX_SUFFIX = ceiversion.apex_suffix
except Exception:
    CEI_APEX_SUFFIX = "242"  # Fallback

# pick the SQLite database to use or use the remote config
local_db_dir = os.environ.get('CEI_NEXUS_LOCAL_DB_DIR', None)

# if one is using a local database file, remote access can be enabled here
allow_remote_access = os.environ.get('CEI_NEXUS_LOCAL_ALLOW_REMOTE_ACCESS', '0')

# a comma separated list of hosts that can access your remote server.
# eg: localhost, 127.0.0.1,
# by default, it is '*', meaning ANY host domain can access your server,
# which is highly insecure, so setting it is recommended when remote
# access is enabled or when Nexus is deployed on a remote server.
allowed_hosts = os.environ.get('CEI_NEXUS_ALLOWED_HOSTS', '*')

# The default behavior is that if you have a locally served database
# only the local host would be allowed to access it.
if (local_db_dir is None) or (allow_remote_access != '0'):
    ALLOWED_HOSTS = allowed_hosts.split(',')
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', ]

SERVER_NAME = ''
if local_db_dir is not None:
    SERVER_NAME = os.path.basename(local_db_dir)
SERVER_NAME = os.environ.get('CEI_NEXUS_SERVER_NAME', SERVER_NAME)

# the version of the REST API
REPORT_REST_API_VERSION = 1.0

# https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.admindocs',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'ceireports.contrib.staticfiles.apps.NexusStaticFilesConfig',
    'guardian',
    'rest_framework',
    'website',
    'data.apps.DataConfig',
    'reports',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication'
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.QueryParameterVersioning'
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'website.middleware.MagicTokenAuthMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'website.middleware.XFrameOptionsMiddleware',
    'website.middleware.TimezoneMiddleware',
    'website.middleware.APIVersionFormatCheckMiddleware',
    'data.middleware.ItemMediaPermissionsMiddleware'
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'website.backends.MagicTokenAuthBackend',
    'website.backends.ObjectPermissionBackend',
]

# In seconds. Default is one day
MAGIC_TOKENS_MAX_AGE = 24 * 60 * 60
MAGIC_TOKEN_QUERY_PARAM = "magic_token"

# Django-guardian settings
GUARDIAN_RAISE_403 = True
# disable monkey patching of user model.
GUARDIAN_MONKEY_PATCH = False
# This is the username of the anonymous user.
# Used to create the anonymous user and subsequently fetch the anonymous user as required.
# If ANONYMOUS_USER_NAME is set to None, anonymous user object permissions-are disabled.
# Defaults to "AnonymousUser".
ANONYMOUS_USER_NAME = None

SILENCED_SYSTEM_CHECKS = ['guardian.W001', ]

ROOT_URLCONF = 'ceireports.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'data.context_processors.global_settings',
                'data.context_processors.request_source',
                'data.context_processors.color_mode',
            ],
        },
    },
]

WSGI_APPLICATION = 'ceireports.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
if local_db_dir is not None:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(local_db_dir, 'db.sqlite3'),
            'USER': 'nexus',
            'PASSWORD': 'cei',
            'HOST': '',
            'PORT': '',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': os.environ.get('CEI_NEXUS_DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.environ.get('CEI_NEXUS_DB_DATABASE_NAME', 'nexus_database'),
            'USER': os.environ.get('CEI_NEXUS_DB_USER', 'nexus'),
            'PASSWORD': os.environ.get('CEI_NEXUS_DB_PASSWORD', 'cei'),
            'HOST': os.environ.get('CEI_NEXUS_DB_HOSTNAME', '127.0.0.1'),
            'PORT': os.environ.get('CEI_NEXUS_DB_PORT', '5432'),
        }
    }

LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login'

# number of items per page
ITEMS_PER_PAGE = 15

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

# This enables timezone support.
# If True:
# 1. datetime objects MUST be saved with timezone('aware'). If not aware,
# Django uses the default timezone('TIME_ZONE') to make it aware, which is unreliable,
# so always specify tzinfo in datetimes.
# 2. Values are still stored in UTC in the DB, but are translated by Django/DRF
# into the end user's timezone using internal tz-aware datetime objects.
# If False, values are stored as naive (without tzinfo), but in local time (as per 'TIME_ZONE')
# NEVER SET THIS TO FALSE.
USE_TZ = True

# default timezone used for template display.
# 1. If the current timezone is not set in Django with activate(),
# this setting is used as a fallback.
# Read: https://docs.djangoproject.com/en/2.2/topics/i18n/timezones/#default-time-zone-and-current-time-zone
# 2. When USE_TZ is False, this is the time zone in which Django will store all datetimes.
# When USE_TZ is True, this is the default time zone that Django will use to display datetimes in templates
# and to interpret datetimes entered in forms.
# 3. If you're running Django on Windows, TIME_ZONE must be set to match the system time zone.
# 'TIME_ZONE' needs to be in Olson format which
# can be very platform and system configuration dependent to set.
if 'CEI_NEXUS_TIMEZONE' in os.environ:
    TIME_ZONE = os.environ['CEI_NEXUS_TIMEZONE']
else:
    import tzlocal
    TIME_ZONE = str(tzlocal.get_localzone())

USE_I18N = True  # enable translation

# Absolute filesystem path to the directory that will hold user-uploaded files.
# Example: "/home/media/media.lawrence.com/media/"
# This can be local to the installation of the sources or local to the folder contain the database
media_dir = os.environ.get('CEI_NEXUS_LOCAL_MEDIA_DIR', local_db_dir or BASE_DIR)

# Unlike static files, in order to serve media files,
# the url has to be manually specified even while using the runserver + DEBUG.
# so we handle this in ceireports/urls.py
# https://docs.djangoproject.com/en/dev/howto/static-files/#serving-files-uploaded-by-a-user-during-development
# Replace '\\' in Windows. Django only accepts Unix-style paths
# This is the Absolute filesystem path to the directory that will hold user-uploaded files.
# Example: "/var/www/files/"
MEDIA_ROOT = os.path.join(media_dir, "media").replace('\\', '/')

# URL that handles the media served from MEDIA_ROOT.
# must end in a slash if set to a non-empty value.
# Examples: "http://media.lawrence.com/media/", "http://example.com/media/"
MEDIA_URL = os.environ.get('CEI_NEXUS_MEDIA_URL_PREFIX', '/media/')

MAX_UPLOAD_SIZE = os.environ.get('CEI_NEXUS_MAX_UPLOAD_SIZE', '5000')
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

# The maximum number of files that may be received via POST in a multipart/form-data encoded
# request before a SuspiciousOperation (TooManyFiles) is raised. You can set this to None to disable the check.
# Applications that are expected to receive an unusually large number of file fields should tune this setting.
# https://docs.djangoproject.com/en/dev/ref/settings/#data-upload-max-number-files
DATA_UPLOAD_MAX_NUMBER_FILES = 50

# 1. ONLY used for the collectstatic command.
# 2. Absolute path to the directory static files should be collected to.
# 3. When using nginx, this should be the directory nginx will be serving out of.
# 4. Don't put anything in this directory yourself; store your static files
# in apps' "static/" subdirectories and in other STATICFILES_DIRS.
# Example: "/home/media/media.lawrence.com/static/"
# similar to MEDIA_ROOT, but for static file serves
STATIC_ROOT = os.path.join(BASE_DIR, 'static').replace('\\', '/')

# In addition to using a static/ directory inside your apps, you can define a list of directories
# (STATICFILES_DIRS) in your settings file where Django will also look for static files.
# files from these dirs are served by Django's django.contrib.staticfiles app when DEBUG is True.
# When DEBUG is False, we serve it using Nginx if run via the Nexus Launcher.
# If multiple files with the same name are present, the first file that is found will be used.
STATICFILES_DIRS = [
    # collect files from utils/remote under STATIC_ROOT: of form (prefix, path)
    ("utils/remote", os.path.join(BASE_DIR, "utils", "remote").replace('\\', '/')),
    ("ansys/nexus", os.path.abspath(os.path.join(BASE_DIR, "..", "ansys", "nexus")).replace('\\', '/')),
]

# relative URL to use when referring to static files located in STATIC_ROOT.
STATIC_URL = '/static/'

# if true, media files via the Django built-in server
# this will be disabled by launcher when using Nginx to serve.
SERVE_STATIC = int(os.environ.get('CEI_NEXUS_SERVE_STATIC_FILES', '1')) == 1

# Analytics tracking code
ANALYTICS_SCRIPT = ''
google_ua = os.environ.get('CEI_NEXUS_GOOGLE_UA', None)  # 'UA-XXXXXXX-Y'
if google_ua is not None:
    ANALYTICS_SCRIPT = "<script>\n"
    ANALYTICS_SCRIPT += " (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\n"
    ANALYTICS_SCRIPT += " (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n"
    ANALYTICS_SCRIPT += " m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n"
    ANALYTICS_SCRIPT += " })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');\n"
    ANALYTICS_SCRIPT += " ga('create', '%s', 'auto');\n" % google_ua
    ANALYTICS_SCRIPT += " ga('send', 'pageview');\n"
    ANALYTICS_SCRIPT += "</script>"

# external nginx frontend server (if any)
CEI_NEXUS_NGINX_URL = os.environ.get('CEI_NEXUS_NGINX_URL', None)

if CEI_NEXUS_NGINX_URL:
    # Use the X-Forwarded-Host (w/ port) from the proxy server if available.
    USE_X_FORWARDED_HOST = True

#  The remote session configuration (websocketserver)
REMOTE_WEBSOCKETURL = None
REMOTE_VNCPASSWORD = None
REMOTE_WS_PORT = None
REMOTE_HTML_PORT = None
# session configuration instance
REMOTE_CONFIGURATION = None
# CEI_NEXUS_REMOTE_WEBSOCKETURL - the URL of the Nginx server connection mapped to websockify
# CEI_NEXUS_REMOTE_VNCPASSWORD - the password for a VNC server
# CEI_NEXUS_REMOTE_WS_PORT - port number of the ws protocol of the websocketserver
# CEI_NEXUS_REMOTE_HTML_PORT - port number of the html protocol of the websocketserver
# Note: the latter two are assumed to be '127.0.0.1' hosted.

# ---Security settings----

# session info like session cookies expire when browser is closed.
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Usually, responses not be served with a 'x-xss-protection: 1; mode=block' header.
# Enable this header to activate the browser's XSS filtering and help prevent XSS attacks.
SECURE_BROWSER_XSS_FILTER = True

# Some browsers will try to guess the content types of the assets that they fetch,
# overriding the Content-Type header. While this can help display sites with improperly
# configured servers, it can also pose a security risk.
# To prevent the browser from guessing the content type and force it to always use the
# type provided in the Content-Type header, you can pass the X-Content-Type-Options: nosniff header
# NOTE: This is left disabled because there are currently issues with Nexus.
# SECURE_CONTENT_TYPE_NOSNIFF = True

# prevents loading Nexus in an <iframe> if set to DENY. Currently allows if request origin is same.
# value of the header to add. Can be SAMEORIGIN or DENY
X_FRAME_OPTIONS = os.environ.get('CEI_NEXUS_X_FRAME_OPTIONS', 'DENY')
# Disable adding the header altogether
DISABLE_X_FRAME_OPTIONS = int(os.environ.get('CEI_NEXUS_DISABLE_X_FRAME_OPTIONS', '0')) == 1

SECURE_REFERRER_POLICY = "no-referrer-when-downgrade"
# WARNING: Should only be turned on if your entire domain is served via HTTPS only.
# i.e. only if the app is deployed on a domain(including subdomains) with SSL.
# May irreversibly break access to your site, if this is ON while using HTTP.
if int(os.environ.get('CEI_NEXUS_HTTPS_SECURED', '0')) == 1:
    # redirects all non-HTTPS requests to HTTPS
    SECURE_SSL_REDIRECT = True

    # avoid transmitting the CSRF cookie over HTTP accidentally.
    CSRF_COOKIE_SECURE = True

    # Whether to use a secure cookie for the session cookie.
    # If this is set to True, the cookie will be marked as 'secure'
    # which means browsers may ensure that the cookie is only sent
    # under an HTTPS connection.
    SESSION_COOKIE_SECURE = True

# For sites that should only be accessed over HTTPS, you can instruct modern browsers
# to refuse to connect to your domain name via an insecure connection (for a given period of time)
# by setting the 'Strict-Transport-Security' header.
# This reduces your exposure to some SSL-stripping man-in-the-middle (MITM) attacks.
# WARNING!
# 1. The HSTS policy applies to your entire domain, not just the URL of the response that you set
# the header on. Therefore, you should only use it if your entire domain is served via HTTPS only.
# 2. Make sure your static files are served over HTTPS as well.
# 3. Also, make sure your SSL certs are not expired, self-signed, or otherwise invalid.
# NOTE: If this is not set when behind a proxy, look at:
# https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-SECURE_PROXY_SSL_HEADER
if int(os.environ.get('CEI_NEXUS_HSTS_SECURED', '0')) == 1:
    # Number of seconds that HSTS header should be respected by the browser.
    # set to one year by default. User will served over HTTPS-only as long as he
    # visits once every year, it keeps resetting to one year.
    # Also note that if you stop serving your site over HTTPS at any point in this
    # one year span, all access to your site is denied from the browser because
    # it always forces to the HTTPS domain which might not exist.
    # For testing, use a small value like 60 and then bump it as needed.
    SECURE_HSTS_SECONDS = int(os.environ.get('CEI_NEXUS_HSTS_SECONDS', '31536000'))

    # This is recommended (assuming all subdomains are served exclusively using HTTPS),
    # otherwise your site may still be vulnerable via an insecure connection to a subdomain.
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# ACLs switch.
# todo: note that this excludes 'add' perm checks which are always ON.
ENABLE_ACLS = int(os.environ.get('CEI_NEXUS_ENABLE_ACLS', 0)) == 1
if ENABLE_ACLS:
    # ACLS_NGINX_LOCATION is the location value of the NGINX configuration where the media file
    # request URLs are directed to.
    # default value is /media_secured
    # If using the default value, your NGINX config would look like:
    # location /media_secured {
    #   internal;
    #   alias /var/www/files;
    # }
    # Will serve /var/www/files/myfile.png when Nexus sets header which will be /media_secured/myfile.png
    # `internal` is very important. It makes sure that location can only be redirected to or accessed internally
    # The `alias` should be where the files are usually uploaded to, i.e CEI_NEXUS_LOCAL_MEDIA_DIR, where it is
    # served out of.
    ACLS_NGINX_LOCATION = os.environ.get('CEI_NEXUS_ACLS_NGINX_LOCATION', '/media_secured')
