# Generated by Django 2.2.1 on 2019-09-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20160629_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='dirname',
            field=models.CharField(blank=True, db_index=True, max_length=256, verbose_name='dataset directory name'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='filename',
            field=models.CharField(blank=True, db_index=True, max_length=256, verbose_name='dataset filename'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='format',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='dataset format'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='tags',
            field=models.CharField(blank=True, db_index=True, max_length=256, verbose_name='userdata'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateTimeField(db_index=True, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='item name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sequence',
            field=models.IntegerField(db_index=True, default=0, verbose_name='index number for a set of items'),
        ),
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='name of the source'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.CharField(blank=True, db_index=True, max_length=256, verbose_name='userdata'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(db_index=True, default='none', max_length=16, verbose_name='item type'),
        ),
        migrations.AlterField(
            model_name='session',
            name='application',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='capture application'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(db_index=True, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='session',
            name='hostname',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='host machine name'),
        ),
        migrations.AlterField(
            model_name='session',
            name='platform',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='system architecture'),
        ),
        migrations.AlterField(
            model_name='session',
            name='tags',
            field=models.CharField(blank=True, db_index=True, max_length=256, verbose_name='userdata'),
        ),
        migrations.AlterField(
            model_name='session',
            name='version',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='application version'),
        ),
    ]
