# Generated by Django 2.2.1 on 2019-11-11 18:37

import uuid

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0006_auto_20190911_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='uid')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='item category name')),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='timestamp')),
            ],
            options={
                'permissions': [('own_itemcategory', 'Owns the item category')],
            },
        ),
        migrations.CreateModel(
            name='ItemCategoryRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.ItemCategory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategoryGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.ItemCategory')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(through='data.ItemCategoryRelation', to='data.ItemCategory', verbose_name='item category list'),
        ),
        migrations.CreateModel(
            name='ItemCategoryUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.ItemCategory')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'permission', 'content_object')},
            },
        ),
        migrations.AddConstraint(
            model_name='itemcategoryrelation',
            constraint=models.UniqueConstraint(fields=('item', 'category'), name='item_category_unique_together'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcategorygroupobjectpermission',
            unique_together={('group', 'permission', 'content_object')},
        ),
    ]
