# Generated by Django 2.2.4 on 2020-01-07 21:49

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20191111_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='guid',
            field=models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='uid'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='item',
            name='guid',
            field=models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='uid'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='session',
            name='guid',
            field=models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='uid'),
        ),
    ]
