# Generated by Django 2.2.7 on 2020-02-18 19:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20200107_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='guid',
            field=models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='uid'),
        ),
    ]
