# Generated by Django 2.2.19 on 2021-08-13 00:13

from ..utils import get_nexus_version
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20200218_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='version',
            field=models.CharField(blank=True, db_index=True, default=get_nexus_version, max_length=20, verbose_name='application version'),
        ),
    ]
