# Generated by Django 2.2.19 on 2021-08-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20210812_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='item category name'),
        ),
    ]
