# Generated by Django 3.2.10 on 2022-02-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20210830_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='tags',
            field=models.TextField(blank=True, db_index=True, verbose_name='userdata'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.TextField(blank=True, db_index=True, verbose_name='userdata'),
        ),
        migrations.AlterField(
            model_name='session',
            name='tags',
            field=models.TextField(blank=True, db_index=True, verbose_name='userdata'),
        ),
    ]
