# Generated by Django 3.2.10 on 2022-03-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20220210_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='item name'),
        ),
    ]
