Set Shell bash
Set FontSize 18
Set Width 800
Set Height 600
Output demo.gif

Hide Sleep 2s Show

Hide
Type "clear"
Enter
Show


# Python library demo
Type "python"
Sleep 3s
Enter

Type "import pydynamicreporting"
Sleep 2s
Enter
# Pause for dramatic effect...
Sleep 4s

Type "help(pydynamicreporting)"
Sleep 2s
Enter
Sleep 6s

Type "pydynamicreporting.__version__"
Sleep 2s
Enter
Sleep 4s

Type "exit()"
Sleep 2s
Enter
Sleep 4s

Hide
Type "clear"
Enter
Show
