"""
Django settings for report_framework project.

Generated by 'django-admin startproject' using Django 4.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['CEI_NEXUS_SECRET_KEY']

# SECURITY WARNING: do not run with debug turned on in production!
DEBUG = int(os.environ.get('CEI_NEXUS_DEBUG', '0')) == 1

BETA_FLAG = os.environ.get('ENSIGHT_ANSYS_BETA_FLAG', '0') != '0'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.admindocs',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'guardian',
    'ansys.dynamicreporting.core.internals.report_framework',
    'ansys.dynamicreporting.core.internals.website',
    'ansys.dynamicreporting.core.internals.data',
    'ansys.dynamicreporting.core.internals.reports',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.media',
                'ansys.dynamicreporting.core.internals.data.context_processors.global_settings',
            ],
        },
    },
]

# pick the SQLite database to use or use the remote config
local_db_dir = os.environ.get('CEI_NEXUS_LOCAL_DB_DIR', None)
# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
if local_db_dir is not None:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(local_db_dir, 'db.sqlite3'),
            'USER': 'nexus',
            'PASSWORD': 'cei',
            'HOST': '',
            'PORT': '',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': os.environ.get('CEI_NEXUS_DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.environ.get('CEI_NEXUS_DB_DATABASE_NAME', 'nexus_database'),
            'USER': os.environ.get('CEI_NEXUS_DB_USER', 'nexus'),
            'PASSWORD': os.environ.get('CEI_NEXUS_DB_PASSWORD', 'cei'),
            'HOST': os.environ.get('CEI_NEXUS_DB_HOSTNAME', '127.0.0.1'),
            'PORT': os.environ.get('CEI_NEXUS_DB_PORT', '5432'),
        }
    }

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# can be very platform and system configuration dependent to set.
if 'CEI_NEXUS_TIMEZONE' in os.environ:
    TIME_ZONE = os.environ['CEI_NEXUS_TIMEZONE']
else:
    import tzlocal

    TIME_ZONE = str(tzlocal.get_localzone())

USE_I18N = True

USE_TZ = True

media_dir = os.environ.get('CEI_NEXUS_LOCAL_MEDIA_DIR', local_db_dir or BASE_DIR)
MEDIA_ROOT = os.path.join(media_dir, "media").replace('\\', '/')
MEDIA_URL = os.environ.get('CEI_NEXUS_MEDIA_URL_PREFIX', '/media/')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static').replace('\\', '/')

# relative URL to use when referring to static files located in STATIC_ROOT.
STATIC_URL = '/static/'

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    # 'django.contrib.staticfiles.finders.DefaultStorageFinder',
]

# In addition to using a static/ directory inside your apps, you can define a list of directories
# (STATICFILES_DIRS) in your settings file where Django will also look for static files.
STATICFILES_DIRS = [
    # collect files from utils/remote under STATIC_ROOT: of form (prefix, path)
    # ("pyadr", os.path.join(BASE_DIR, "pyadr").replace('\\', '/')),  # todo
    ("ansys/nexus", os.path.abspath(os.path.join(BASE_DIR, "..", "ansys", "nexus")).replace('\\', '/')),
]

# https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

ENABLE_ACLS = int(os.environ.get('CEI_NEXUS_ENABLE_ACLS', 0)) == 1

# disable monkey patching of user model.
GUARDIAN_MONKEY_PATCH = False
# This is the username of the anonymous user.
# Used to create the anonymous user and subsequently fetch the anonymous user as required.
# If ANONYMOUS_USER_NAME is set to None, anonymous user object permissions-are disabled.
# Defaults to "AnonymousUser".
ANONYMOUS_USER_NAME = None

