# Generated by Django 2.2.1 on 2019-09-11 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_ComplexReportParameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='template',
            name='master',
            field=models.BooleanField(db_index=True, default=True, verbose_name='master template'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='report name'),
        ),
        migrations.AlterField(
            model_name='template',
            name='report_type',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='report type'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tags',
            field=models.CharField(blank=True, db_index=True, max_length=256, verbose_name='userdata'),
        ),
    ]
