# Generated by Django 2.2.4 on 2020-01-07 21:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20190911_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='guid',
            field=models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='uid'),
        ),
    ]
