# Generated by Django 2.2.7 on 2020-02-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20200107_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='children_order',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='children order'),
        ),
    ]
