# Generated by Django 2.2.4 on 2021-01-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20200204_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='children_order',
            field=models.TextField(blank=True, default='', verbose_name='children order'),
        ),
    ]
