name: Create Draft Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  draft-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed to create a release & upload artifacts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: '0'
          fetch-tags: true

      - name: Set up Env
        uses: ./.github/actions/setup-env

      - name: Run version checks
        run: make check-version

      - name: Check for existing release
        run: |
          if gh release view "${{ github.ref_name }}" > /dev/null 2>&1; then
            echo "❌ Release for tag '${{ github.ref_name }}' already exists."
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build library source and wheel artifacts
        uses: ./.github/actions/build-library
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Create Draft GitHub Release with Artifacts
        run: |
          gh release create "${{ github.ref_name }}" \
            --title "Release ${GITHUB_REF_NAME}" \
            --notes "See [CHANGELOG.md](./CHANGELOG.md)" \
            --draft \
            dist/*
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
