# Failing action: https://github.com/ansys/pydynamicreporting/actions/runs/17598170413
name: Security Scan

on:
  push:
    branches:
      - main
      - release/*
  workflow_dispatch:

jobs:
  security_scan:
    if: false
    uses: ansys-internal/ci-templates/.github/workflows/security-scan-mend.yml@v7
    with:
      package_type: 'poetry+npm'
      needs: 'sca,sast,sbom'
    secrets: inherit
